apiVersion: apps/v1
kind: Deployment
metadata:
  name: pokeapi
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: pokeapi
  template:
    metadata:
      labels:
        app: pokeapi
    spec:
      containers:
      - image: docker.io/library/pokeapi:0.1
        name: pokeapi
        ports:
        - containerPort: 3000
        env:
        - name: POKEDEX_NAME
          valueFrom:
            configMapKeyRef:
              name: pokeapi
              key: POKEDEX_NAME
        - name: POKEDEX_START_NUMBER
          valueFrom:
            configMapKeyRef:
              name: pokeapi
              key: POKEDEX_START_NUMBER
        - name: POKEDEX_END_NUMBER
          valueFrom:
            configMapKeyRef:
              name: pokeapi
              key: POKEDEX_END_NUMBER
